
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 104
#define YY_END_OF_BUFFER 105
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[301] =
    {   0,
        0,    5,  105,  104,    6,    4,    4,  104,  104,    7,
       62,   66,  104,   77,   78,   58,   56,   83,   57,   85,
       60,   18,   18,   84,   86,   71,   87,   72,   63,  103,
      103,  103,  103,  103,  103,   79,  104,   80,   68,  102,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,   81,   67,   82,
       69,    5,    2,    2,    3,    4,   76,    0,   17,    0,
        0,    7,   94,   95,    0,   17,    0,   59,   91,   89,
       90,   88,    0,   19,   61,   92,    0,   19,   18,    0,
        0,    0,   20,    0,    0,    0,   18,   70,   64,   73,

       75,   74,   65,  103,    0,    0,  103,  103,  103,  103,
        1,    1,   97,  103,  103,   41,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
       53,  103,   29,   34,  103,  103,  103,   54,  103,  103,
      103,  103,  103,  103,  103,  103,   96,    5,    2,    2,
        2,   17,    0,    0,    0,  100,  101,    0,   19,   93,
       18,    0,    0,   18,    0,   19,    0,   18,    0,   18,
       99,   98,  103,  103,  103,  103,  103,   36,  103,  103,
      103,  103,  103,  103,  103,   42,   47,  103,  103,  103,
      103,  103,  103,   38,  103,  103,  103,    8,  103,  103,

      103,   49,  103,  103,  103,   10,   40,  103,  103,  103,
        0,    0,    0,    0,    0,    0,    0,    0,   19,  103,
       26,   31,  103,  103,  103,  103,  103,   11,  103,  103,
      103,   13,   52,   23,  103,  103,  103,   43,  103,  103,
      103,   12,  103,   25,  103,  103,  103,   50,  103,    0,
        0,    0,   21,  103,  103,  103,   51,   22,   27,   32,
      103,  103,  103,    9,  103,  103,  103,  103,   30,  103,
       45,   55,   17,    0,   17,  103,  103,   46,  103,   28,
      103,   48,   24,   39,  103,   35,    0,  103,  103,  103,
       33,  103,    0,   14,   15,   37,   44,    0,   16,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,    1,   29,   30,   31,   30,   30,   32,   33,
       34,   34,   34,   35,   34,   34,   34,   36,   37,   34,
       34,   38,   34,   39,   40,   34,   34,   41,   34,   34,
       42,   43,   44,   45,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   34,   63,   64,   65,   66,   34,   67,   68,
       69,   34,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    1,    1,    1,
        5,    1,    1,    1,    1,    1,    1,    1,    1,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    6,
        6,    6,    6,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    1,    1,    1,    6,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[309] =
    {   0,
        0,   72,  530,  531,  531,    0,  526,  501,   69,    0,
      500,  499,   67,  531,  531,   65,  498,  531,   53,   64,
       64,  109,  171,  497,  531,   62,  496,   66,  531,    0,
       88,  461,   90,  458,   89,  531,   99,  531,  493,  473,
       47,   42,   48,   62,   40,  111,  460,  104,   73,  456,
      453,  468,  164,  449,  450,   70,  457,  531,  484,  531,
      531,  131,    0,  507,  531,    0,  531,  130,  502,  490,
      136,    0,  531,  531,  110,  496,  488,  478,  531,  531,
      531,  531,  486,  178,  476,  531,  198,  210,  260,  138,
      141,  228,  531,  216,  140,  232,    0,  531,  475,  531,

      531,  531,  474,    0,  145,  165,  198,  442,  439,  432,
      531,  494,  531,   99,  446,  126,  448,  433,  442,  445,
      431,  144,  441,  192,  440,  428,  426,  423,  233,  424,
        0,  422,  418,    0,  423,  417,  147,    0,  416,  424,
      413,  414,  407,  420,  409,  422,  531,  178,  531,  469,
        0,  531,  221,  232,  203,  531,  531,  237,  266,  531,
      451,  248,  118,  256,  287,  298,  293,  316,  219,  278,
      531,  531,  406,  418,  417,  407,  419,    0,  414,  404,
      408,  404,  414,  396,  394,    0,    0,  393,  405,  405,
      404,  407,  406,    0,  393,  403,  389,    0,  401,  383,

      389,    0,  382,  381,  378,    0,    0,  385,  388,  383,
      283,  286,  422,  296,  261,  285,  421,  325,  335,  372,
        0,    0,  361,  356,  345,  354,  336,    0,  337,  329,
      335,    0,    0,    0,  327,  330,  322,    0,  339,  320,
      332,    0,  318,    0,  327,  313,  322,    0,  319,  318,
      320,  289,    0,  303,  314,  299,    0,    0,    0,    0,
      300,  294,  295,    0,  294,  286,  303,  285,    0,  237,
        0,    0,  323,  324,  329,  238,  233,    0,  208,    0,
      172,    0,    0,    0,  178,    0,  328,  158,  121,   68,
        0,   32,  334,    0,    0,    0,    0,  342,  531,  531,

      391,  398,  405,  412,  414,  418,  424,  431
    } ;

static const flex_int16_t yy_def[309] =
    {   0,
      300,    1,  300,  300,  300,  301,  301,  300,  302,  303,
      300,  300,  304,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  305,
      305,  305,  305,  305,  305,  300,  300,  300,  300,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  300,  300,  300,
      300,  300,  301,  301,  300,  301,  300,  302,  300,  300,
      302,  303,  300,  300,  304,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,   89,
      300,  300,  300,  300,  306,  300,   23,  300,  300,  300,

      300,  300,  300,  305,  302,  304,  305,  305,  305,  305,
      300,  300,  300,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  300,  300,  300,  300,
      301,  300,  307,  302,  308,  300,  300,  300,  300,  300,
       89,  300,  300,  300,  300,  300,  300,  300,  306,  306,
      300,  300,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      307,  307,  300,  302,  308,  308,  300,  300,  300,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  307,
      302,  308,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  307,  302,  308,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  302,  305,  305,  305,
      305,  305,  302,  305,  305,  305,  305,  302,  300,    0,

      300,  300,  300,  300,  300,  300,  300,  300
    } ;

static const flex_int16_t yy_nxt[605] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   23,   23,   24,   25,   26,   27,   28,   29,   30,
       30,   30,   31,   30,   30,   32,   30,   33,   34,   35,
       30,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   30,   48,   30,   30,   49,   30,   50,
       51,   52,   53,   54,   55,   35,   56,   30,   57,   58,
       59,   60,   61,   62,   63,   69,   64,   76,   78,   81,
       82,   83,   85,   84,   84,   84,   84,   99,  100,  297,
       86,   79,  102,  103,  105,  105,  105,  124,  106,  106,

      106,  111,  118,  112,  119,  120,  115,  125,  121,   77,
      116,   70,  122,  117,   71,   87,  123,  105,  296,  135,
      152,  106,  107,  144,  145,  107,   88,  136,   89,   90,
       90,   90,  148,  149,  108,  150,  152,  164,  164,   91,
       92,  107,  152,   93,  162,   94,  169,  163,  107,   95,
      107,   69,   77,  176,   87,  131,   91,   90,  177,   92,
      164,  164,  132,  133,   93,  126,  295,  134,  127,   94,
      105,  128,   70,  129,  106,   76,   95,   96,   70,  148,
      149,  154,  150,  162,  158,  169,  163,   70,   88,  179,
       97,   97,   97,   97,  180,  186,  107,  159,  159,  159,

      159,  187,   92,  294,  105,   93,  201,   77,  106,   92,
      140,  202,   93,  216,  141,  107,   96,  161,   90,   90,
       90,   92,  167,  158,  292,  300,   93,  212,   92,   84,
       84,   84,   84,   93,  165,  168,  168,  168,  152,  105,
      291,   92,  165,  106,   93,  217,  189,  166,  166,  166,
      166,   97,   97,   97,   97,  190,  159,  159,  159,  159,
       92,  167,  163,  213,  300,   93,   87,   90,   90,   90,
       90,  216,  158,  290,   70,  164,  164,   88,  289,   89,
       90,   90,   90,  288,  169,  159,  159,  159,  159,  212,
      214,   92,  250,  195,   93,  252,  286,   92,  165,  275,

       93,  163,  152,  217,  218,   87,  166,  166,  166,  166,
       92,  158,  168,  168,  168,   93,   92,  219,  219,  219,
      219,   93,  167,  169,  273,  213,  152,  217,  213,  273,
      152,  217,   93,  285,  152,  168,  168,  168,   70,  275,
      152,  218,  251,  218,  219,  219,  219,  219,  299,  284,
      283,  282,  281,   93,  219,  219,  219,  219,  280,  279,
      213,  167,   70,  278,  277,  213,   70,  276,  272,   93,
       70,  217,  271,  293,  274,  270,   70,  269,  268,  298,
      218,  267,  266,  287,   70,  265,  264,  263,  262,  261,
       93,   65,  260,  259,   65,   65,   65,   65,   68,   68,

      258,   68,  257,   68,   68,   72,   72,  256,   72,   72,
       72,   72,   75,   75,  255,  254,   75,   75,   75,  104,
      104,  170,  253,  170,  211,  211,  211,  211,  211,  211,
      211,  215,  215,  215,  215,  215,  215,  215,  215,  211,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      161,  149,  210,  209,  208,  207,  206,  205,  204,  203,
      200,  199,  198,  197,  196,  194,  193,  192,  191,  188,
      185,  184,  183,  182,  181,  178,  111,  175,  174,  173,

      172,  171,  160,  157,  156,   75,  155,   68,  153,  151,
      147,  146,  143,  142,  139,  138,  137,  130,  114,  113,
      110,  109,  101,   98,   80,   74,   73,   67,   66,  300,
        3,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300
    } ;

static const flex_int16_t yy_chk[605] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    9,    2,   13,   16,   19,
       19,   20,   21,   20,   20,   20,   20,   26,   26,  292,
       21,   16,   28,   28,   31,   35,   33,   45,   31,   35,

       33,   37,   42,   37,   42,   43,   41,   45,   43,   13,
       41,    9,   44,   41,    9,   22,   44,   46,  290,   49,
       75,   46,   33,   56,   56,   31,   22,   49,   22,   22,
       22,   22,   62,   62,   31,   62,   68,  163,  163,   22,
       22,   33,   71,   22,   90,   22,   95,   91,   46,   22,
       31,  105,   75,  114,   22,   48,   22,   90,  114,   22,
       91,   91,   48,   48,   22,   46,  289,   48,   46,   22,
       53,   46,   68,   46,   53,  106,   22,   23,   71,  148,
      148,   71,  148,   90,   84,   95,   91,  105,   23,  116,
       23,   23,   23,   23,  116,  122,   53,   84,   84,   84,

       84,  122,   23,  288,  107,   23,  137,  106,  107,   84,
       53,  137,   84,  155,   53,   53,   23,   87,   87,   87,
       87,   23,   94,   84,  285,  169,   23,  153,   84,   88,
       88,   88,   88,   84,   92,   94,   94,   94,  154,  129,
      281,   88,   92,  129,   88,  155,  124,   92,   92,   92,
       92,   96,   96,   96,   96,  124,  158,  158,  158,  158,
       88,   94,  164,  153,  169,   88,   89,  162,  162,  162,
      162,  215,  159,  279,  154,  164,  164,   89,  277,   89,
       89,   89,   89,  276,  170,  159,  159,  159,  159,  211,
      154,   89,  212,  129,   89,  216,  270,  159,   92,  252,

      159,  164,  214,  215,  166,   89,  165,  165,  165,  165,
       89,  159,  167,  167,  167,   89,  159,  166,  166,  166,
      166,  159,  168,  170,  250,  211,  251,  216,  212,  273,
      274,  252,  166,  268,  287,  168,  168,  168,  214,  275,
      293,  219,  214,  166,  218,  218,  218,  218,  298,  267,
      266,  265,  263,  166,  219,  219,  219,  219,  262,  261,
      250,  168,  251,  256,  255,  273,  274,  254,  249,  219,
      287,  275,  247,  287,  251,  246,  293,  245,  243,  293,
      219,  241,  240,  274,  298,  239,  237,  236,  235,  231,
      219,  301,  230,  229,  301,  301,  301,  301,  302,  302,

      227,  302,  226,  302,  302,  303,  303,  225,  303,  303,
      303,  303,  304,  304,  224,  223,  304,  304,  304,  305,
      305,  306,  220,  306,  307,  307,  307,  307,  307,  307,
      307,  308,  308,  308,  308,  308,  308,  308,  217,  213,
      210,  209,  208,  205,  204,  203,  201,  200,  199,  197,
      196,  195,  193,  192,  191,  190,  189,  188,  185,  184,
      183,  182,  181,  180,  179,  177,  176,  175,  174,  173,
      161,  150,  146,  145,  144,  143,  142,  141,  140,  139,
      136,  135,  133,  132,  130,  128,  127,  126,  125,  123,
      121,  120,  119,  118,  117,  115,  112,  110,  109,  108,

      103,   99,   85,   83,   78,   77,   76,   70,   69,   64,
       59,   57,   55,   54,   52,   51,   50,   47,   40,   39,
       34,   32,   27,   24,   17,   12,   11,    8,    7,    3,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[105] =
    {   0,
1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 5 "lexer.l"
    #include <bits/stdc++.h>
	#include "parser.tab.h"
    using namespace std;
    bool indentation_flag = false;
    bool newline_flag = true;
    //bool initial_line_ident = true;
	string text_block;
    stack<int> indentation_checking;  // make it extern variable
    int spaceCount = 0;
    void err (const char* s) {
        if(s == NULL) {
            printf("Error in memory allocation");
            exit(0);
        }
    }

#line 726 "lex.yy.c"
#line 727 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 66 "lexer.l"


#line 950 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 301 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 531 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 68 "lexer.l"
{
    
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 72 "lexer.l"
{
    // cout << "Blank line " << yylineno << endl;
    yylval.strval = strdup(yytext);
    return NEWLINE;
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 78 "lexer.l"
{
    // cout << "No whitespace after new line " << yylineno << " and the lexeme is " << yytext << endl;
    if(newline_flag)
    {
        char *copy_string = strdup(yytext);
        for (int i = yyleng - 1; i >= 0; --i )
            unput(copy_string[i]);
        free(copy_string);
        newline_flag = false;
        yylval.strval = strdup(yytext);
        //printf("newline_next_is_empty %d\n", yylineno);
        return NEWLINE;
    }
    else
    {
        while(!indentation_checking.empty() && indentation_checking.top() > 0)
        {
            char *copy_string = strdup(yytext);
            for (int i = yyleng - 1; i >= 0; --i )
                unput(copy_string[i]);
            free(copy_string);
            indentation_checking.pop();
            // cout << "1. DEDENT " << yylineno << endl;;
            return DEDENT;
        }
        newline_flag = true;
    }

}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 108 "lexer.l"
{ 
    // cout << "NEWLINE " << yylineno << endl;
    spaceCount = 0;
    yylval.strval = strdup(yytext);
    // printf("normal newline %d\n", yylineno);
    return NEWLINE;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 116 "lexer.l"
{
    // cout << "Entering case 3 " << yylineno << endl;
    if(indentation_checking.empty()) {
        indentation_checking.push(0);
    }
    string whitespace = strdup(yytext);
    int wspace_tab = count(whitespace.begin(), whitespace.end(), '\t');
    int wspace_space = count(whitespace.begin(), whitespace.end(), ' ');
    int total = wspace_tab * 4 + wspace_space;
    if(total == indentation_checking.top()) {
        indentation_flag = false;
    }
    else if(total > indentation_checking.top()) {
        // // cout << indentation_checking.top() << endl;
        if(!indentation_flag) {
            // cout << "PUSHED " << total << " on line " << yylineno << endl;
            indentation_checking.push(total);
            return INDENT;
        }
        else {
            // printf("Indentation Error \n");
            exit(0);
        }
    }
    else {
        while(indentation_checking.top() != 0 && total < indentation_checking.top()) {
            char *copy_string = strdup(yytext);
            for (int i = yyleng - 1; i >= 0; --i)
                unput(copy_string[i]);
                yy_set_bol(1);
            free(copy_string);
            // stack <int> temp;
            // while(!indentation_checking.empty()) {
            //     temp.push(indentation_checking.top());
            //     // cout << "TOP " << indentation_checking.top() << endl;
            //     indentation_checking.pop();
            // }
            // while(!temp.empty()) {
            //     indentation_checking.push(temp.top());
            //     temp.pop();
            // }
            // cout << indentation_checking.top() << " " << yylineno << endl;
            indentation_checking.pop();
            indentation_flag = true;
            // cout << "3. DEDENT " << yylineno << endl;;
            return DEDENT;
        }
    }
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 166 "lexer.l"
{
    while(indentation_checking.top() != 0) {
        char *copy_string = strdup(yytext);
        for (int i = yyleng - 1; i >= 0; --i)
            unput(copy_string[i]);
            yy_set_bol(1);
        free(copy_string);
        indentation_checking.pop();
        indentation_flag = true;
        return DEDENT;
    }
    return 0;
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 180 "lexer.l"
{
    // cout << "WHITESPACE PURANA\n";
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 184 "lexer.l"
{
    // cout << "COMMENT\n";
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 188 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return TYPE_INT;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 193 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return TYPE_FLOAT;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 198 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return TYPE_STRING;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 203 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return TYPE_BOOL;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 208 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return TYPE_LIST;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 213 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return TYPE_DICT;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 218 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DUNDER_INIT;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 223 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DUNDER_NAME;    
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 228 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DUNDER_MAIN;
}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 233 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return STRING_LITERAL;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 238 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return INTEGER;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 243 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return FLOAT_NUMBER;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 248 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return IMAGINARY_NUMBER;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 253 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_FALSE;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 258 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_AWAIT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 263 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_ELSE;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 268 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_IMPORT;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 273 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_PASS;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 278 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_NONE;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 283 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_BREAK;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 288 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_EXCEPT;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 293 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_IN;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 298 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_RAISE;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 303 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_TRUE;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 308 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_CLASS;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 313 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_FINALLY;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 318 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_IS;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 323 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_RETURN;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 328 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_AND;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 333 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_CONTINUE;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 338 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_FOR;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 343 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_LAMBDA;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 348 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_TRY;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 353 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_AS;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 358 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_DEF;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 363 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_FROM;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 368 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_NONLOCAL;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 373 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_WHILE;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 378 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_ASSERT;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 383 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_DEL;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 388 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_GLOBAL;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 393 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_NOT;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 398 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_WITH;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 403 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_ASYNC;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 408 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_ELIF;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 413 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_IF;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 418 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_OR;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 423 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return KEY_YIELD;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 428 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_ADD;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 433 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_SUBTRACT;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 438 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_MULTIPLY;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 443 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_POWER;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 448 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_DIVIDE;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 453 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_FLOOR_DIVIDE;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 458 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_MODULO;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 463 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_AT;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 468 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_LEFT_SHIFT;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 473 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_RIGHT_SHIFT;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 478 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_BITWISE_AND;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 483 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_BITWISE_OR;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 488 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_BITWISE_XOR;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 493 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_BITWISE_NOT;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 498 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_ASSIGN;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 503 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_LESS_THAN;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 508 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_GREATER_THAN;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 513 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_LESS_THAN_EQUAL;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 518 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_GREATER_THAN_EQUAL;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 523 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_EQUAL;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 528 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return OP_NOT_EQUAL;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 533 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_LEFT_PAREN;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 538 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_RIGHT_PAREN;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 543 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_LEFT_BRACKET;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 548 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_RIGHT_BRACKET;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 553 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_LEFT_CURLY;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 558 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_RIGHT_CURLY;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 563 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_COMMA;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 568 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_COLON;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 573 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_DOT;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 578 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_SEMICOLON;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 583 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 588 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ARROW;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 593 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_ADD;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 598 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_SUBTRACT;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 603 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_MULTIPLY;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 608 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_DIVIDE;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 613 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_FLOOR_DIVIDE;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 618 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_MODULO;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 623 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_BITWISE_AND;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 628 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_BITWISE_OR;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 633 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_BITWISE_XOR;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 638 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_RIGHT_SHIFT;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 643 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_LEFT_SHIFT;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 648 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ASSIGN_POWER;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 653 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return DELIM_ELLIPSIS;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 658 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return WILDCARD_UNDERSCORE;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 663 "lexer.l"
{
    yylval.strval = strdup(yytext);
    return NAME;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 668 "lexer.l"
ECHO;
	YY_BREAK
#line 1944 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 301 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 301 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 300);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 668 "lexer.l"

